/** Navigation 路由名常量 */
export class RouteNames {
  static readonly VIDEO_DETAIL: string = 'videoDetail';
  static readonly VIDEO_FULLSCREEN: string = 'videoFullscreen';
  static readonly LOGIN: string = 'login';
  static readonly SEARCH_RESULT: string = 'searchResult';
  static readonly LIVE: string = 'live';
  static readonly LIVE_ROOM: string = 'liveRoom';
  static readonly FAVORITES: string = 'favorites';
  static readonly FAVORITE_DETAIL: string = 'favoriteDetail';
  static readonly HISTORY: string = 'history';
  static readonly WATCH_LATER: string = 'watchLater';
  static readonly USER_SPACE: string = 'userSpace';
  static readonly DYNAMIC_DETAIL: string = 'dynamicDetail';
  static readonly PUBLISH_DYNAMIC: string = 'publishDynamic';
  static readonly TOPIC: string = 'topic';
  static readonly TOPIC_FEED: string = 'topicFeed';
  static readonly BANGUMI: string = 'bangumi';
  static readonly BANGUMI_DETAIL: string = 'bangumiDetail';
  static readonly MUSIC: string = 'music';
}
